version: "3.4"
services:
  ais-vdm-simulator:
    image: ais-vdm-simulator:latest
    build: .
    container_name: ais-vdm-simulator
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      # Redis Settings
      REDIS_HOST   : 10.0.100.20  # Redis Host. Default is 10.0.100.20
      REDIS_PORT   : 6379         # Redis Port. Default is 6379
      # Target settings
      TARGET_HOST  : 10.0.100.20  # Host, which receives VDM msg. Default is 10.0.100.20
      TARGET_PORT  : 6503          # Port. Default is 6503 
      SEND_PERIOD  : 2             # Sending period [sec]